app:
  name: 'golang-template'
  env: 'dev'
  port: 3000
web:
  prefork: true
jwt: 
  accessTokenExpired: '8h'
  refreshTokenExpired: '12h'
  secretKey: "this-super-secret-key"
database: 
  username: 'root'
  password: 'root'
  host: 'localhost'
  port: 3306
  autoMigration: true
  name: 'golang-template'
  pool: 
    idle: 10
    max: 100
    lifetime: 300